@startuml
class Member
class BoardMember
class Event
class Conference
class BoardMeeting
class Location
class Person
class AAUOC

skinparam groupInheritance 2
Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember
AAUOC o-- Location
AAUOC o-- Person
AAUOC o-- Event
Event -- Location
BoardMeeting -- BoardMember
Conference -- Person
Event -- Member


@enduml